#!/bin/sh
sbatch enrichment_runall_introgressed_spliceai_weak_v2.sh
sbatch enrichment_runall_introgressed_spliceai_moderate_v2.sh
sbatch enrichment_runall_introgressed_spliceai_strong_v2.sh
sbatch enrichment_runall_introgressed_spliceai_sig_v2.sh
sbatch enrichment_runall_adaptive_spliceai_weak_v2.sh
sbatch enrichment_runall_adaptive_spliceai_moderate_v2.sh
sbatch enrichment_runall_adaptive_spliceai_strong_v2.sh
sbatch enrichment_runall_adaptive_spliceai_sig_v2.sh
