#!/bin/sh
filter_runall_enrichment_GTEx_QTLs.sh
filter_runall_enrichment_SpliceAI.sh
filter_runall_enrichment_VEP.sh

enrichment_runall_GTEx_QTLs_v2.sh
enrichment_runall_SpliceAI_v2.sh
enrichment_runall_VEP_v2.sh

visualize_GTEx_QTLs_runall_enrichment.sh
