#!/bin/sh

# for manuscript
Rscript visualize_GTEx_QTLs_region_adaptively.R
Rscript visualize_GTEx_QTLs_region_introgressed.R

Rscript visualize_GTEx_QTLs_region_LDtagN_adaptively.R
Rscript visualize_GTEx_QTLs_region_LDtagN_introgressed.R

Rscript visualize_GTEx_QTLs_region_LDtagN_direct_compare_introgressed.R
Rscript visualize_GTEx_QTLs_region_LDtagN_direct_compare_introgressed_noLDtagN.R

Rscript visualize_GTEx_QTLs_region_LDtagN_direct_compare_introgressed_SpliceAI.R
Rscript visualize_GTEx_QTLs_region_LDtagN_direct_compare_introgressed_SpliceAI_noLDtagN.R

Rscript visualize_GTEx_QTLs_AF_LD_v2.R
