#!/bin/sh
Rscript mapsy_to_variant_table_updated.R
Rscript mapsy_to_variant_table_updated_figures_weak.R
Rscript mapsy_to_variant_table_updated_figures_strong_neg.R
Rscript mapsy_to_variant_table_updated_figures_strong_pos.R
